version: '3.9'

services:
  redis-server:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - test
    volumes:
      - ~/volumes/redis:/var/lib/redis
    command: redis-server --requirepass password

  redis_exporter:
    container_name: redis_exporter
    image: oliver006/redis_exporter
    networks:
      - test
    ports:
      - 9121:9121
    command: ["--redis.addr", "redis://redis:6379", "--redis.password", "password"]

  prometheus-server:
    container_name: prometheus-server
    image: prom/prometheus
    ports:
      - 9090:9090
    links:
      - redis-server:redis-server
      - redis_exporter:redis_exporter
    networks:
      - test
      - test2
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana-ui:
    container_name: grafana-server
    image: grafana/grafana
    ports:
      - 3000:3000
    links:
      - prometheus-server:prometheus
    networks:
      - test2
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-230105VaM}

networks:
  test:
  test2:
