global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'prometheus-stack-monitor'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['172.30.0.247:9090']

  - job_name: redis_exporter
    static_configs:
    - targets: ['172.30.0.247:9121']
