global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'prometheus-stack-monitor'

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

  - job_name: redis_exporter
    static_configs:
    - targets: ['redis_exporter:9121']
